[package]
name = "bale-vercel-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }

bale-signaling = {
    git = "https://github.com/kookoo1sabzy/BaleVPN.git",
    branch = "main"
}

lk-signaling = {
    git = "https://github.com/kookoo1sabzy/BaleVPN.git",
    branch = "main"
}
